#!/bin/sh
# Get current branch name
branch=$(git rev-parse --abbrev-ref HEAD)

if [ $branch = reports ]; then
    echo Deinitializing submodules for reports branch...
    git submodule deinit -f --all
	rm -rf libs/arfit libs/scintillation_models/refactored_tppsm libs
elif [ $branch = main ]; then
    echo Initializing submodules for main branch...
    git submodule update --init --recursive
fi